public class myCustomSettingDemo {
   /* public void callTrigger(){
        MyCustomSetting__c mcs  = new MyCustomSetting__c.getInstance('mydataset');
        System.debug('Value of isActive = '+mcs.isActive__c);
        if (mcs.isActive__c==true){
            System.debug('Please call the trigger');
        }
        else{
            system.debug('Dont call the trigger');
        }
        
    }
*/
}